### PR TITLE
cleanup for all package lists

### PR DESCRIPTION
**Pull request by gotenksIN**

### CODE REVIEW

**Comment by rikmills** [comment]
You still have some duplicates.

In desktop-amd64: alsa-base, fonts-dejavu-core, inputattach, spice-vdagent, ubuntu-drivers-common
In desktop-recommends-amd64: gnome-font-viewer, wrussian

I would in suggest in future using sort | uniq (or sort -u) for something like this, and putting the sort/uniq changes in a single commit if as in this case they are are related change over multiple files.

While update.cfg is a bit irrelevant at the moment because the meta is being updated manually, instead of being automatically generated by germinate from a set of seed files in another repo, I would note on adding the papirus PPA url that it would be better for whatever is needed from that PPA for Eoan to be copied across to the stable cinnamon remix PPA. You should not depend on PPAs that are outside of a project's direct control for flavour development tasks.

For Focal, the latest 20191201 release of papirus-icon-theme is already in the main Ubuntu archive.

There is no debian/changelog entry documenting your changes.

**Comment by rikmills** [comment]
Just realised, I should have done this in review changes. I'll carry on here anyway for this one.

Regards the 'fixups' I assume the removal of arc/numix this is deliberate under 'Added/Removed GTK themes'. If so, it should really say exactly what was added and removed.

Likewise, 'cleaned up package lists should be a bit more verbose'. Perhaps 'Cleaned up package lists, sorting files and removing duplicates.'

Also, your changelog entries for yourself should be continuous, e.g. no line separation. So like

```
ubuntucinnamon-meta (0.1.2) focal; urgency=medium

  * Change 1
  * Change 2

 -- Omkar Chandorkar <forumomkar@gmail.com>  Wed, 1 Jan 2020 17:24:48 +0530
```

Hope that helps!

**Comment by rikmills** [comment]
Oh, there also remains a duplicate 'inputattach' in desktop-amd64

**Comment by JPeisach** [comment]
Nice job, are we ready to merge?

**Comment by gotenksIN** [comment]
idk how I wrote the wrong spelling of changelog in commit name, everything should be fixed by now

**Comment by anunaym14** [comment]
> Nice job, are we ready to merge?

I think so

**Review by anunaym14 — APPROVED** [review]

**Pull request merged**
